name: Update README
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # PROYECTOS: Mostramos las capturas grandes
      - name: Update Projects
        uses: sarisia/actions-readme-feed@v1
        with:
          url: "https://www.broslunas.com/rss.xml"
          file: "README.md"
          start_flag: ""
          end_flag: ""
          whitelist: "https://broslunas.com/projects/.*"
          max_posts: 3
          format: |
            <a href="${url}" target="_blank">
              <img src="${image}" width="250" alt="${title}" style="border-radius:10px; margin: 10px;"/>
            </a>

      # BLOG: Solo texto para no saturar
      - name: Update Blog
        uses: sarisia/actions-readme-feed@v1
        with:
          url: "https://www.broslunas.com/rss.xml"
          file: "README.md"
          start_flag: ""
          end_flag: ""
          whitelist: "https://broslunas.com/blog/.*"
          max_posts: 5
          format: "- [${title}](${url})"

      # CERTIFICADOS: Miniaturas al final
      - name: Update Certs
        uses: sarisia/actions-readme-feed@v1
        with:
          url: "https://www.broslunas.com/rss.xml"
          file: "README.md"
          start_flag: ""
          end_flag: ""
          whitelist: "https://broslunas.com/certificates/.*"
          max_posts: 6
          format: |
            <a href="${url}" target="_blank">
              <img src="${image}" height="80" title="${title}" style="margin: 5px;"/>
            </a>

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización automática de Portfolio (Imágenes OK)"